name = "decision-guardian-telemetry"
main = "worker.ts"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "TELEMETRY_KV"
id = "6d5d5f96934d4d5097c0526d6662d366"
preview_id = "6d5d5f96934d4d5097c0526d6662d366"
